spring:
  profiles:
    active: postgres
  flyway:
    enabled: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true

spring-helper:
  export-path: ./output
  is-create-record: true
  is-create-mapper: true
  is-create-entity: true
  is-create-query: true
  is-create-repository: true

export-class:
  record-class:
    template-path: templates/RecordClass.vm
    encoding: UTF-8
    suffix: Record
    extension: .kt
    package-name: com.slave.infrastructure.mapper.record
    export-path: /record
  mapper-class:
    template-path: templates/MapperClass.vm
    encoding: UTF-8
    suffix: Mapper
    extension: .kt
    package-name: com.slave.infrastructure.mapper
    export-path:
  entity-class:
    template-path: templates/EntityClass.vm
    encoding: UTF-8
    suffix:
    extension: .kt
    package-name: com.slave.domain.entity
    export-path: /entity
  query-interface:
    template-path: templates/QueryInterface.vm
    encoding: UTF-8
    suffix: Query
    extension: .kt
    package-name: com.slave.domain.query
    export-path: /query
  repository-interface:
    template-path: templates/RepositoryInterface.vm
    encoding: UTF-8
    suffix: Repository
    extension: .kt
    package-name: com.slave.domain.repository
    export-path: /repository

logging:
  level:
    org:
      springframework: INFO
    com:
      springhelper:
        infrastructure:
          mapper: DEBUG
